package id.turus.stasiuncuaca;
import android.app.Activity; import android.os.Bundle; import android.content.Context; import android.widget.*; import android.text.InputType; import java.util.Locale;
public class SettingsActivity extends Activity {
 private android.content.SharedPreferences p; private EditText title,channel,readKey,aiKey,aiModel,crop,lat,lon,elev; private Spinner cult; private TextView toggleRead,toggleAi;
 @Override public void onCreate(Bundle b){super.onCreate(b); setContentView(R.layout.activity_settings); p=getSharedPreferences("thingspeak_config",Context.MODE_PRIVATE); title=findViewById(R.id.appTitle);channel=findViewById(R.id.channel);readKey=findViewById(R.id.readKey);aiKey=findViewById(R.id.aiKey);aiModel=findViewById(R.id.aiModel);crop=findViewById(R.id.crop);lat=findViewById(R.id.latitude);lon=findViewById(R.id.longitude);elev=findViewById(R.id.elevation);cult=findViewById(R.id.cultivation);toggleRead=findViewById(R.id.toggleReadKey);toggleAi=findViewById(R.id.toggleAiKey); cult.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,new String[]{"Konvensional / PHT","Organik"})); ((ArrayAdapter<String>)cult.getAdapter()).setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item); load(); findViewById(R.id.useGps).setOnClickListener(v->startActivity(new android.content.Intent(this,MainActivity.class))); findViewById(R.id.saveSettings).setOnClickListener(v->save()); findViewById(R.id.cancelSettings).setOnClickListener(v->finish()); toggleRead.setOnClickListener(v->toggle(readKey,toggleRead));toggleAi.setOnClickListener(v->toggle(aiKey,toggleAi)); }
 private void load(){title.setText(p.getString("app_title","STASIUN CUACA"));channel.setText(p.getString("channel",""));readKey.setText(p.getString("read_key",""));aiKey.setText(p.getString("ai_api_key",""));aiModel.setText(p.getString("ai_model","gpt-6-luna"));crop.setText(p.getString("crop","Tanaman pertanian"));lat.setText(f(p.getFloat("latitude",Float.NaN)));lon.setText(f(p.getFloat("longitude",Float.NaN)));elev.setText(f(p.getFloat("elevation",Float.NaN))); cult.setSelection(p.getString("farm_cultivation_mode","Konvensional / PHT").toLowerCase(Locale.US).contains("organik")?1:0);}
 private String f(float x){return Float.isFinite(x)?String.format(Locale.US,"%.6f",x):"";}
 private void save(){String tv=title.getText().toString().trim(); if(tv.isEmpty())tv="STASIUN CUACA"; String cv=crop.getText().toString().trim(); if(cv.isEmpty())cv="Tanaman pertanian"; float la=num(lat.getText().toString()),lo=num(lon.getText().toString()),el=num(elev.getText().toString()); if(!Float.isFinite(la)||la<-90||la>90){lat.setError("Latitude -90..90");return;} if(!Float.isFinite(lo)||lo<-180||lo>180){lon.setError("Longitude -180..180");return;} p.edit().putString("app_title",tv).putString("channel",channel.getText().toString().trim()).putString("read_key",readKey.getText().toString().trim()).putString("ai_api_key",aiKey.getText().toString().trim()).putString("ai_model",aiModel.getText().toString().trim().isEmpty()?"gpt-6-luna":aiModel.getText().toString().trim()).putString("crop",cv).putFloat("latitude",la).putFloat("longitude",lo).putFloat("elevation",Float.isFinite(el)?el:Float.NaN).putString("farm_cultivation_mode",cult.getSelectedItem().toString()).apply(); Toast.makeText(this,"Pengaturan tersimpan.",Toast.LENGTH_SHORT).show(); finish();}
 private float num(String s){try{return Float.parseFloat(s.trim().replace(',','.'));}catch(Exception e){return Float.NaN;}}
 private void toggle(EditText e,TextView t){boolean vis=e.getInputType()==(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD);e.setInputType(InputType.TYPE_CLASS_TEXT|(vis?InputType.TYPE_TEXT_VARIATION_PASSWORD:InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD));t.setText(vis?"TAMPILKAN":"SEMBUNYIKAN");e.setSelection(e.length());}
}
